apiVersion: v1
kind: Service
metadata:
  name: buttertech-service
  namespace: buttertech
spec:
  selector:
    app: buttertech-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
